name: Build and publish a Docker image

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_LABEL: latest

jobs:
  release:
    runs-on: ubuntu-latest       
    steps:
      - name: upgrade scheduler
        shell: bash
        run: |
          curl -u "${{ secrets.RANCHER_ACCESS }}:${{ secrets.RANCHER_KEY }}" \
          -X POST \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -d '{"inServiceStrategy": {"imageUuid": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }}"}}' \
          'https://rancher.dev.economia.gov.br/v2-beta/projects/1a656207/services/1s5647/?action=upgrade'       
          
