name: Build, publish and release a Docker image

on:
  push:
#     branches: [ main ]
    tags:
      - '*'
    
env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_LABEL: latest

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }}
          
  release:
  
    needs: build-and-push-image
    runs-on: ubuntu-latest
    
    steps:
      - name: upgrade worker
        uses: sekassel-research/actions-rancher-update@1.1.4
        with:
          rancher_url: https://rancher.dev.economia.gov.br
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: 1a656207
          stack_name: airflow2-hmg
          service_name: airflow-worker
          docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }}    
          
      - name: upgrade scheduler
        uses: sekassel-research/actions-rancher-update@1.1.4
        with:
          rancher_url: https://rancher.dev.economia.gov.br
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: 1a656207
          stack_name: airflow2-hmg
          service_name: airflow-scheduler
          docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }}            
    
      - name: upgrade flower
        uses: sekassel-research/actions-rancher-update@1.1.4
        with:
          rancher_url: https://rancher.dev.economia.gov.br
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: 1a656207
          stack_name: airflow2-hmg
          service_name: flower
          docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }}

      - name: upgrade webserver
        uses: sekassel-research/actions-rancher-update@1.1.4
        with:
          rancher_url: https://rancher.dev.economia.gov.br
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: 1a656207
          stack_name: airflow2-hmg
          service_name: airflow-webserver
          docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }}
          
    steps:
      - name: upgrade worker-85
        uses: sekassel-research/actions-rancher-update@1.1.4
        with:
          rancher_url: https://rancher.dev.economia.gov.br
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: 1a656207
          stack_name: airflow2-hmg
          service_name: airflow-worker-85
          docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }}    
          
    steps:
      - name: upgrade worker-bigmemory
        uses: sekassel-research/actions-rancher-update@1.1.4
        with:
          rancher_url: https://rancher.dev.economia.gov.br
          rancher_access: ${{ secrets.RANCHER_ACCESS }}
          rancher_key: ${{ secrets.RANCHER_KEY }}
          project_id: 1a656207
          stack_name: airflow2-hmg
          service_name: airflow-worker-bigmemory
          docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }}              
